<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SideMenuSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $data = [
            [
                'name'        => 'Dashboard',
                'title'       => 'Dashboard',
                'slug'        => 'dashboard',
                'url'         => '/dashboard',
                'is_parent'   => 0,
                'menu_order'  => 1,
                'icon'        => 'fas fa-tachometer-alt',
                'parent_id'   => null,
                'permissions' => null,
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Vehical',
                'title'       => 'Vehical',
                'slug'        => 'vehical',
                'url'         => '/vehicles/check-in',
                'is_parent'   => 1,
                'menu_order'  => 2,
                'icon'        => 'fas fa-sign-in-alt',
                'parent_id'   => null,
                'permissions' => 'add_vehicle',
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Vehical Check In',
                'title'       => 'Check In',
                'slug'        => 'vehical-check-in',
                'url'         => '/vehicles/checkin/create',
                'is_parent'   => 0,
                'menu_order'  => 1,
                'parent_id'   => 2,
                'icon'        => 'fas fa-sign-in-alt',
                'permissions' => 'add_vehicle',
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Vehical Check Out',
                'title'       => 'Check Out',
                'slug'        => 'vehical-check-out',
                'url'         => '/vehicles/check-out',
                'is_parent'   => 0,
                'menu_order'  => 2,
                'parent_id'   => 2,
                'icon'        => 'fas fa-sign-out-alt',
                'permissions' => 'mark_checked_out',
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            // [
            //     'name'        => 'Add Vendors',
            //     'title'       => 'Add Vendors',
            //     'slug'        => 'add-vendors',
            //     'url'         => '/vendors/add',
            //     'is_parent'   => 0,
            //     'menu_order'  => 4,
            //     'icon'        => 'fas fa-user-plus',
            //     'parent_id'   => null,
            //     'permissions' => 'add_vendor',
            //     'description' => null,
            //     'created_at'  => $now,
            //     'updated_at'  => $now,
            // ],
            [
                'name'        => 'Add Purchase',
                'title'       => 'Add Purchase',
                'slug'        => 'add-purchase',
                'url'         => '/purchase/add',
                'is_parent'   => 0,
                'menu_order'  => 5,
                'icon'        => 'fas fa-cart-plus',
                'parent_id'   => null,
                'permissions' => 'add_product',
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'View Purchase Order',
                'title'       => 'View PO',
                'slug'        => 'view-purchase-order',
                'url'         => '/purchase/orders',
                'is_parent'   => 0,
                'menu_order'  => 6,
                'icon'        => 'fas fa-file-alt',
                'parent_id'   => null,
                'permissions' => 'view_vehicle_history',
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'User Management',
                'title'       => 'User Management',
                'slug'        => 'user-management',
                'url'         => 'users',
                'is_parent'   => 1,
                'menu_order'  => 7,
                'icon'        => 'fas fa-users-cog',
                'parent_id'   => null,
                'permissions' => 'manage_users',
                'description' => 'Manage users and roles',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Manage Users',
                'title'       => 'Manage Users',
                'slug'        => 'manage-users',
                'url'         => '/users',
                'is_parent'   => 0,
                'menu_order'  => 1,
                'icon'        => 'fas fa-user',
                'parent_id'   => 7, // assuming User Management gets id = 8
                'permissions' => 'manage_users',
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Manage Roles',
                'title'       => 'Manage Roles',
                'slug'        => 'manage-roles',
                'url'         => '/roles',
                'is_parent'   => 0,
                'menu_order'  => 2,
                'icon'        => 'fas fa-user-shield',
                'parent_id'   => 7,
                'permissions' => 'assign_roles',
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'System Settings',
                'title'       => 'Settings',
                'slug'        => 'settings',
                'url'         => '/settings',
                'is_parent'   => 0,
                'menu_order'  => 8,
                'icon'        => 'fas fa-cogs',
                'parent_id'   => null,
                'permissions' => 'access_settings',
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'System Logs',
                'title'       => 'Logs',
                'slug'        => 'logs',
                'url'         => '/logs',
                'is_parent'   => 0,
                'menu_order'  => 9,
                'icon'        => 'fas fa-file-alt',
                'parent_id'   => null,
                'permissions' => 'view_logs',
                'description' => null,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

        ];

        $this->db->table('side_menu')->insertBatch($data);
    }
}
